version: '3.2'

services:
  jupyter:
    container_name: jupyter
    build:
      context: .
      dockerfile: ./jupyter/Dockerfile
    command: jupyter lab
    volumes:
      - ./jupyter:/notebooks
      - jupyter_settings:/home/jovyan/.jupyter
    ports:
      - 8888:8888
    env_file:
      - ./config/jupyter.env
      - ./config/minio.env
    depends_on:
      - postgres

  minio:
    container_name: minio
    image: minio/minio
    command: server /data
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
    env_file:
      - ./config/minio.env

  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./config/postgres.env

  airflow:
    container_name: airflow
    image: puckel/docker-airflow
    command: webserver
    volumes:
      - ./dags:/usr/local/airflow/dags
    ports:
      - 8080:8080
    env_file:
      - ./config/postgres.env
      - ./config/minio.env
      - ./config/database.env
    environment:
      - EXECUTOR=Local
    depends_on:
        - postgres

  # metabase:
  #   image: metabase/metabase
  #   depends_on:
  #     - db
  #   ports:
  #     - 5000:3000
  #   networks:
  #     - webnet
  #   volumes:
  #     - ./metabase_data:/metabase-data
  #   environment:
  #     MB_DB_FILE: /metabase-data/metabase.db

volumes:
  jupyter_settings:
