version: '3.2'

x-airflow-common:
  &airflow-common
  image: apache/airflow
  volumes:
    - ./dags:/opt/airflow/dags
  env_file:
    - ./.env.airflow
  depends_on:
    - postgres

services:
  jupyter:
    container_name: jupyter
    build:
      context: .
      dockerfile: ./jupyter/Dockerfile
    command: jupyter lab
    volumes:
      - ./jupyter:/notebooks
      - ./jupyter/jupyter_notebook_config.py:/home/jovyan/.jupyter/jupyter_notebook_config.py
      - ./jupyter/templates:/home/jovyan/.jupyter/templates
      - jupyter_settings:/home/jovyan/.jupyter
    ports:
      - 8888:8888
    env_file:
      - ./.env.jupyter
      - ./.env.minio
    depends_on:
      - postgres

  minio:
    container_name: minio
    image: minio/minio
    command: server /data --console-address ":9001"
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
      - 9001:9001
    env_file:
      - ./.env.minio

  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - 54321:5432
    env_file:
      - ./.env.postgres

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    command: webserver
    ports:
      - 8080:8080

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    command: scheduler

  # airflow-worker:
  #   <<: *airflow-common
  #   container_name: airflow_worker
  #   entrypoint: /bin/bash
  #   command: celery worker

  # airflow-flower:
  #   <<: *airflow-common
  #   container_name: airflow_flower
  #   entrypoint: /bin/bash
  #   command: celery flower
  #   ports:
  #     - 5555:5555

  # metabase:
  #   image: metabase/metabase
  #   depends_on:
  #     - db
  #   ports:
  #     - 5000:3000
  #   networks:
  #     - webnet
  #   volumes:
  #     - ./metabase_data:/metabase-data
  #   environment:
  #     MB_DB_FILE: /metabase-data/metabase.db

volumes:
  jupyter_settings:
